web:
  cors:
    allowed-origins: "*"
    allowed-methods: GET
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

email:
  username: "username"
  password: "password"

std-gpt:
  base-url: "http://localhost:18080"

logging:
  level:
    root: debug

server:
  port: 18081