email:
  username: "username"
  password: "password"
  smtp:
    host: "smtp.gmail.com"
    port: 25
    ssl:
      trust: "smtp.gmail.com"

std-gpt:
  base-url: "http://localhost:18080"

logging:
  level:
    root: info

server:
  port: 18081